# Generated by Django 6.0.3 on 2026-04-17 13:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InvoiceApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='created_at',
        ),
        migrations.AddField(
            model_name='agentrole',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='agent_roles', to=settings.AUTH_USER_MODEL, verbose_name='Entreprise'),
        ),
        migrations.AddField(
            model_name='paymenttype',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='payment_types', to=settings.AUTH_USER_MODEL, verbose_name='Entreprise'),
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/', verbose_name='Image du produit'),
        ),
        migrations.AddField(
            model_name='user',
            name='add_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name="Date d'inscription"),
        ),
        migrations.AddField(
            model_name='user',
            name='company_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Adresse email'),
        ),
        migrations.AddField(
            model_name='user',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='company_logos/', verbose_name="Logo de l'entreprise"),
        ),
        migrations.AlterField(
            model_name='agentrole',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nom du rôle'),
        ),
        migrations.AlterField(
            model_name='paymenttype',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nom du type de paiement'),
        ),
        migrations.AlterUniqueTogether(
            name='agentrole',
            unique_together={('company', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='paymenttype',
            unique_together={('company', 'name')},
        ),
    ]
