# Generated by Django 6.0.6 on 2026-09-25 20:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InvoiceApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='paymenttype',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='paymenttype',
            name='company',
        ),
        migrations.AlterField(
            model_name='agentrole',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_roles', to=settings.AUTH_USER_MODEL, verbose_name='Entreprise'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='plan',
            field=models.CharField(choices=[('test', 'Test (200 FCFA)'), ('monthly', 'Mensuel'), ('annual', 'Annuel')], max_length=10, verbose_name='Plan choisi'),
        ),
        migrations.AlterField(
            model_name='subscriptionpayment',
            name='plan',
            field=models.CharField(choices=[('test', 'Test (200 FCFA)'), ('monthly', 'Mensuel'), ('annual', 'Annuel')], max_length=10, verbose_name='Plan payé'),
        ),
        migrations.DeleteModel(
            name='PaymentMethod',
        ),
        migrations.DeleteModel(
            name='PaymentType',
        ),
    ]
