# Generated by Django 6.0.6 on 2026-09-25 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InvoiceApp', '0002_alter_paymenttype_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockload',
            name='engine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_loads', to='InvoiceApp.engine', verbose_name='Engin utilisé'),
        ),
    ]
