# Generated by Django 6.0.6 on 2026-09-29 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InvoiceApp', '0003_stockload_engine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='plan',
            field=models.CharField(choices=[('essential_monthly', 'Essentiel — Mensuel (6 000 FCFA / mois)'), ('essential_annual', 'Essentiel — Annuel (50 000 FCFA / an)'), ('business_monthly', 'Business — Mensuel (8 000 FCFA / mois)'), ('business_annual', 'Business — Annuel (60 000 FCFA / an)'), ('monthly', 'Essentiel — Mensuel'), ('annual', 'Essentiel — Annuel'), ('test', 'Test temporaire')], max_length=30, verbose_name='Plan choisi'),
        ),
        migrations.AlterField(
            model_name='subscriptionpayment',
            name='plan',
            field=models.CharField(choices=[('essential_monthly', 'Essentiel — Mensuel (6 000 FCFA / mois)'), ('essential_annual', 'Essentiel — Annuel (50 000 FCFA / an)'), ('business_monthly', 'Business — Mensuel (8 000 FCFA / mois)'), ('business_annual', 'Business — Annuel (60 000 FCFA / an)'), ('monthly', 'Essentiel — Mensuel'), ('annual', 'Essentiel — Annuel'), ('test', 'Test temporaire')], max_length=30, verbose_name='Plan payé'),
        ),
    ]
