# Generated by Django 6.0.6 on 2026-10-05 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InvoiceApp', '0004_alter_subscription_plan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='whatsapp_delivered_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de remise WhatsApp'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='whatsapp_delivery_status',
            field=models.CharField(blank=True, choices=[('pending', 'En attente'), ('sent', 'Envoyé'), ('delivered', 'Remis'), ('read', 'Lu'), ('failed', 'Échec')], max_length=20, null=True, verbose_name='Statut remise WhatsApp'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='whatsapp_message_id',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='ID message WhatsApp Meta'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='whatsapp_read_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de lecture WhatsApp'),
        ),
    ]
