"""
Django settings for InvoiceProject project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-ly8$wnu(bk8=b^$gvwz$)z0cmwbhd$#oin)jp7492qzqa^s_2t'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'InvoiceApp',
]

AUTH_USER_MODEL = 'InvoiceApp.User'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'InvoiceApp.middleware.SubscriptionAccessMiddleware',
]

ROOT_URLCONF = 'InvoiceProject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'InvoiceApp.context_processors.subscription_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'InvoiceProject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

# Media files (upload d'images pour logo et produits)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Configuration de l'authentification
LOGIN_URL = '/login/'

# ═══════════════════════════════════════════════════════════════
# Configuration MoneyFusion / FusionPay (paiement des abonnements)
# ═══════════════════════════════════════════════════════════════
# Récupérez votre URL d'API unique depuis votre tableau de bord MoneyFusion
# (créez une "application" sur https://moneyfusion.net pour l'obtenir). Ne mettez
# jamais cette URL en dur en production : utilisez une variable d'environnement.
MONEYFUSION_API_URL = os.environ.get('MONEYFUSION_API_URL', '')

# URL de vérification du statut d'un paiement (GET, {token} remplacé par le tokenPay
# renvoyé à l'initialisation). ⚠️ À confirmer/ajuster auprès du support MoneyFusion ou
# de docs.moneyfusion.net : le format ci-dessous est celui observé dans l'écosystème
# FusionPay au moment de l'écriture de ce code, mais n'a pas pu être vérifié par un
# appel réel (voir README_ABONNEMENT.md).
MONEYFUSION_STATUS_CHECK_TEMPLATE = os.environ.get(
    'MONEYFUSION_STATUS_CHECK_TEMPLATE',
    'https://www.pay.moneyfusion.net/paiementNotif/{token}',
)

# URL publique de base de votre site, utilisée pour construire webhook_url et
# return_url envoyés à MoneyFusion. À changer en production (ex: https://monapp.com).
SITE_BASE_URL = os.environ.get('SITE_BASE_URL', 'http://127.0.0.1:8000')
