"""
Django settings for InvoiceProject project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Charge les variables définies dans le fichier .env à la racine du projet
# (créé côté serveur, jamais versionné — voir .env.example pour le modèle).
load_dotenv(BASE_DIR / '.env')

# ═══════════════════════════════════════════════════════════════
# Assistant IA (Gemini) — bouton flottant présent sur les pages de l'app
# ═══════════════════════════════════════════════════════════════
# Clé API Google AI Studio. Laissez vide pour désactiver l'assistant
# (le widget affichera un message d'indisponibilité au lieu de planter).
GEMINI_API_KEY = os.getenv('GEMINI_API_KEY', '')
# Modèle Gemini utilisé côté serveur pour les appels de fonctions.
GEMINI_MODEL = os.getenv('GEMINI_MODEL', 'gemini-2.5-flash')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Lue depuis .env — ne JAMAIS committer de vraie clé. Le fallback ci-dessous
# n'est utilisable qu'en local (il est volontairement marqué "insecure").
SECRET_KEY = os.environ.get(
    'SECRET_KEY',
    'django-insecure-CHANGE-ME-en-dev-uniquement-ne-jamais-utiliser-en-prod',
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'True') == 'True'

# Domaines/IP autorisés à servir l'app, séparés par des virgules dans .env.
# Ex: ALLOWED_HOSTS=monapp.com,www.monapp.com
ALLOWED_HOSTS = [h.strip() for h in os.environ.get('ALLOWED_HOSTS', '').split(',') if h.strip()]

# Origines de confiance pour les requêtes POST cross-origin protégées par CSRF
# (nécessaire dès que l'app est servie en HTTPS derrière un domaine réel).
# Ex: CSRF_TRUSTED_ORIGINS=https://monapp.com,https://www.monapp.com
CSRF_TRUSTED_ORIGINS = [o.strip() for o in os.environ.get('CSRF_TRUSTED_ORIGINS', '').split(',') if o.strip()]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'InvoiceApp',
]

AUTH_USER_MODEL = 'InvoiceApp.User'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'InvoiceApp.middleware.SubscriptionAccessMiddleware',
]

ROOT_URLCONF = 'InvoiceProject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'InvoiceApp.context_processors.subscription_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'InvoiceProject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

# Media files (upload d'images pour logo et produits)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Configuration de l'authentification
LOGIN_URL = '/login/'

# ═══════════════════════════════════════════════════════════════
# Configuration MoneyFusion / FusionPay (paiement des abonnements)
# ═══════════════════════════════════════════════════════════════
# Récupérez votre URL d'API unique depuis votre tableau de bord MoneyFusion
# (créez une "application" sur https://moneyfusion.net pour l'obtenir). Ne mettez
# jamais cette URL en dur en production : utilisez une variable d'environnement.
MONEYFUSION_API_URL = os.environ.get('MONEYFUSION_API_URL', '')

# URL de vérification du statut d'un paiement (GET, {token} remplacé par le tokenPay
# renvoyé à l'initialisation). ⚠️ À confirmer/ajuster auprès du support MoneyFusion ou
# de docs.moneyfusion.net : le format ci-dessous est celui observé dans l'écosystème
# FusionPay au moment de l'écriture de ce code, mais n'a pas pu être vérifié par un
# appel réel (voir README_ABONNEMENT.md).
MONEYFUSION_STATUS_CHECK_TEMPLATE = os.environ.get(
    'MONEYFUSION_STATUS_CHECK_TEMPLATE',
    'https://www.pay.moneyfusion.net/paiementNotif/{token}',
)

# URL publique de base de votre site, utilisée pour construire webhook_url et
# return_url envoyés à MoneyFusion. À changer en production (ex: https://monapp.com).
SITE_BASE_URL = os.environ.get('SITE_BASE_URL', 'http://127.0.0.1:8000')

# ═══════════════════════════════════════════════════════════════
# Configuration email (envoi des liens de réinitialisation de mot de passe)
# ═══════════════════════════════════════════════════════════════
# Par défaut (développement) : les emails sont affichés dans la console au lieu
# d'être réellement envoyés. En production, configurez un vrai serveur SMTP via
# les variables d'environnement ci-dessous (ex: Gmail, SendGrid, Mailgun, etc.).
EMAIL_BACKEND = os.environ.get(
    'EMAIL_BACKEND',
    'django.core.mail.backends.console.EmailBackend',
)
EMAIL_HOST = os.environ.get('EMAIL_HOST', '')
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', '587'))
EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'True') == 'True'
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', 'no-reply@votre-domaine.com')

# Durée de validité d'un lien de réinitialisation de mot de passe (en secondes).
# 86400 = 24 heures.
PASSWORD_RESET_TIMEOUT = int(os.environ.get('PASSWORD_RESET_TIMEOUT', '86400'))

# ═══════════════════════════════════════════════════════════════
# Sécurité production — actif uniquement quand DEBUG=False (via .env)
# ═══════════════════════════════════════════════════════════════
# En local (DEBUG=True), ces réglages sont désactivés pour ne pas gêner le
# développement (pas de HTTPS local, pas de domaine réel).
if not DEBUG:
    # Redirige tout le trafic HTTP vers HTTPS.
    SECURE_SSL_REDIRECT = os.environ.get('SECURE_SSL_REDIRECT', 'True') == 'True'
    # Nécessaire si l'app est derrière un proxy/load balancer qui termine le TLS
    # (Nginx, Render, Railway, etc.) pour que Django sache que la requête est HTTPS.
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

    # Les cookies de session et CSRF ne doivent circuler qu'en HTTPS.
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

    # HSTS : force le navigateur à toujours utiliser HTTPS pour ce domaine.
    # Démarrez avec une valeur basse (ex: 3600) le temps de valider le déploiement
    # HTTPS, puis augmentez (ex: 31536000 = 1 an) une fois confiant.
    SECURE_HSTS_SECONDS = int(os.environ.get('SECURE_HSTS_SECONDS', '3600'))
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

    # Empêche le navigateur de deviner le type MIME d'un fichier (protection XSS).
    SECURE_CONTENT_TYPE_NOSNIFF = True

    # Interdit l'affichage du site dans une <iframe> sur un autre domaine
    # (protection contre le clickjacking). XFrameOptionsMiddleware l'applique déjà
    # par défaut à 'DENY' ; on le rend explicite ici.
    X_FRAME_OPTIONS = 'DENY'
